// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAS-kT0lHA3i1frYRHegOtMO2Z_wuqlgs',
    appId: '1:206546233243:android:3fd0c0b3f663d30707633e',
    messagingSenderId: '206546233243',
    projectId: 'project-cinderella-test',
    storageBucket: 'project-cinderella-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvP25IqOWay1NeZfbNkb-B_cb3qkgfbXM',
    appId: '1:206546233243:ios:5fa2ac301740e17007633e',
    messagingSenderId: '206546233243',
    projectId: 'project-cinderella-test',
    storageBucket: 'project-cinderella-test.appspot.com',
    androidClientId: '206546233243-thleaf25g0h0trssireoc9eec4ijuhs6.apps.googleusercontent.com',
    iosClientId: '206546233243-gkuoc2hudb395all1vagv682drl00fnl.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectCinderellaTest2',
  );
}
